#matrix operations:add,sub,mul,transpose,inverse,determinent

In [2]:
import numpy as np
matrix_1=np.array([[1,2,3],[4,5,6] ])
matrix_2=np.array([ [1,2,3],[4,5,6] ] )
matrix_3=np.array([ [3,2,3],[4,5,6] ] )
addition=np.add(matrix_1,matrix_3)
subtraction=np.subtract(matrix_1,matrix_2)
print(f"addition={addition}")
print(f"subtraction={subtraction}")

print(matrix_1+matrix_3)
print(matrix_1-matrix_2)

addition=[[ 4  4  6]
 [ 8 10 12]]
subtraction=[[0 0 0]
 [0 0 0]]
[[ 4  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [4]:
import numpy as np
matrix_1=np.array([[1,2,3],[4,5,6] ])
matrix_2=np.array([ [1,2,3],[4,5,6] ] )
mul=np.dot(matrix_1,matrix_2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [1]:
import numpy as np
matrix_1=np.array([[1,2],[4,5] ])
matrix_2=np.array([ [1,2,3],[4,5,6] ] )
mul=np.dot(matrix_1,matrix_2)
print(f"multiplication={mul}")
#print(matrix_1@matrix_2)

multiplication=[[ 9 12 15]
 [24 33 42]]


In [8]:
 
import numpy as np


# Create matrix
matrix = np.array([
                   [1,4,3],
                   [2,5,5],
                   [3,4,4]          
                            ])

# Calculate inverse of matrix
print(np.linalg.inv(matrix))



[[ 0.         -0.57142857  0.71428571]
 [ 1.         -0.71428571  0.14285714]
 [-1.          1.14285714 -0.42857143]]
[[ 0.         -0.57142857  0.71428571]
 [ 1.         -0.71428571  0.14285714]
 [-1.          1.14285714 -0.42857143]]


In [10]:
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix using T attribute
print(matrix.T)
# Transpose matrix using numpy transpose method
print(np.transpose(matrix))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 14, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

-4.996003610813198e-15

In [3]:
import numpy as np
import scipy
matrix_A=np.array([[0,0,1],[0,0,0],[0,1,0] ])
#compressed sparse row
sparse_A=scipy.sparse.csr_matrix(matrix_A)
print(sparse_A)

  (0, 2)	1
  (2, 1)	1


In [14]:
#select one or more elements in a vector or matrix.
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
print(vector[2])

3

In [15]:
# Select second row, second column
print(matrix[1,1])

5


In [16]:
#select first 3 elements of a vector
print(vector[0:3])
# Select all elements of a vector
vector[:]

[1 2 3]


array([1, 2, 3, 4, 5, 6])

In [17]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [18]:
# Select the last element
vector[-1]

6

In [19]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [5]:
#brodcasting:adding a scalar to matrix
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[4,6,7]])
array2=np.array([1,3,5])
brodcasting_1=np.add(array1,5)
brodcasting_2=np.add(array1,array2)
print(f"brodcasting={brodcasting_1}")
print(f"brodcasting={brodcasting_2}")


brodcasting=[[ 6  7  8]
 [ 9 10 11]
 [ 9 11 12]]
brodcasting=[[ 2  5  8]
 [ 5  8 11]
 [ 5  9 12]]
