In [2]:
import sklearn
#sklearn comes with toy data sets to practice machine learning techniques
#they are available under a module datasets

In [2]:
from sklearn import datasets

print(dir(datasets))
#The dir() function returns all properties and methods of the specified object,

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_california_housing', '_covtype', '_kddcup99', '_lfw', '_olivetti_faces', '_openml', '_rcv1', '_samples_generator', '_species_distributions', '_svmlight_format_fast', '_svmlight_format_io', '_twenty_newsgroups', 'clear_data_home', 'dump_svmlight_file', 'fetch_20newsgroups', 'fetch_20newsgroups_vectorized', 'fetch_california_housing', 'fetch_covtype', 'fetch_kddcup99', 'fetch_lfw_pairs', 'fetch_lfw_people', 'fetch_olivetti_faces', 'fetch_openml', 'fetch_rcv1', 'fetch_species_distributions', 'get_data_home', 'load_boston', 'load_breast_cancer', 'load_diabetes', 'load_digits', 'load_files', 'load_iris', 'load_linnerud', 'load_sample_image', 'load_sample_images', 'load_svmlight_file', 'load_svmlight_files', 'load_wine', 'make_biclusters', 'make_blobs', 'make_checkerboard', 'make_circles', 'make_classification', 'make_friedman1', 'make_friedman2', 'make

In [3]:
iris=datasets.load_iris() #this method returns a bunch
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [ ]:
Bunch is a subclass of the Dict class and supports all the methods as dict does.
In addition, it allows you to use the keys as attributes.
   
dict_1 = {"a":1, "b":2}
bunch_1 = Bunch(a=1, b=2)
dict_1[b]
bunch_1['b']====>2
dict_1.b===>error
bunch_1.b====>2


In [5]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
import pandas as pd
#lets create a data frame from the iris data set.
df = pd.DataFrame(iris.data, columns = iris.feature_names)
#print(df.head())
df['target'] = iris.target
#X = iris.data
#print(df.head())
print(df.sample(4))

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
143                6.8               3.2                5.9               2.3   
94                 5.6               2.7                4.2               1.3   
39                 5.1               3.4                1.5               0.2   
148                6.2               3.4                5.4               2.3   

     target  
143       2  
94        1  
39        0  
148       2  


In [ ]:
#create your first model implem
#Logistic regression is a linear classifier. 
Despite the name it is actually a classification algorithm.

In [7]:
 df.sample(4)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
38                4.4               3.0                1.3               0.2   
98                5.1               2.5                3.0               1.1   
34                4.9               3.1                1.5               0.2   
78                6.0               2.9                4.5               1.5   

    target  
38       0  
98       1  
34       0  
78       1

In [2]:
# Imports
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

# Load Data
iris = load_iris()

# Create a dataframe
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target

# Let's see a sample of created df
print(df.sample(4))

# Let's see target names
targets = iris.target_names
print(targets)          #['setosa' 'versicolor' 'virginica']
# Prepare training data for building the model
X_train = df.drop(['target'], axis=1)

y_train = df['target']

# Instantiate the model
cls = LogisticRegression()

# Train/Fit the model 
cls.fit(X_train, y_train)

# Make prediction using the model
X_pred = [15.1, 3.2, 10.5, 5.5]
y_pred = cls.predict([X_pred])

print(f"Prediction class={y_pred}")

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
67                5.8               2.7                4.1               1.0   
33                5.5               4.2                1.4               0.2   
73                6.1               2.8                4.7               1.2   
31                5.4               3.4                1.5               0.4   

    target  
67       1  
33       0  
73       1  
31       0  
['setosa' 'versicolor' 'virginica']
Prediction class=[2]


C:\Users\kgnan\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
# Load Data
iris = load_iris()

# Create a dataframe
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target

# Let's see a sample of created df
print(df.sample(4))

#df.info(),df.shape

# Let's see target names
targets = iris.target_names
print(targets)          #['setosa' 'versicolor' 'virginica']
# Prepare training data for building the model
X_train = df.drop(['target'], axis=1)

y_train = df['target']

# Instantiate the model
cls = KNeighborsClassifier()

# Train/Fit the model 
cls.fit(X_train, y_train)

# Make prediction using the model
X_pred = [15.1, 3.2, 11.5, 10.5]
y_pred = cls.predict([X_pred])

print(f"Prediction class={y_pred}")

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
4                 5.0               3.6                1.4               0.2   
84                5.4               3.0                4.5               1.5   
43                5.0               3.5                1.6               0.6   
25                5.0               3.0                1.6               0.2   

    target  
4        0  
84       1  
43       0  
25       0  
['setosa' 'versicolor' 'virginica']
Prediction class=[2]


In [ ]:
#split the training data into a training set and test set and use the test set 
#to evaluate what the model has learned; this is known as offline evaluation. 
#There are several ways to split data into train and test sets
#scikit-learn has a built-in function to do this on our behalf called "" train_test_split(). ""

In [46]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
# Load Data
iris = load_iris()

# Create a dataframe
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target

# Let's see a sample of created df
print(df.sample(4))

#df.info(),df.shape

# Let's see target names
targets = iris.target_names
print(targets)          #['setosa' 'versicolor' 'virginica']
# Prepare data for building the model
X = df.drop(['target'], axis=1)

y = df['target']
# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=.7,random_state=25)


print(f"Train size: {round(len(X_train) / len(X) * 100)}% \nTest size: {round(len(X_test) / len(X) * 100)}%")

# Instantiate the model
cls = KNeighborsClassifier()

# Train/Fit the model 
cls.fit(X_train, y_train)

# Make prediction using the model
X_pred = [5.1, 3.2, 1.5, 0.5]
y_pred = cls.predict([X_pred])

print(f"Prediction class={y_pred}")


     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
104                6.5               3.0                5.8               2.2   
126                6.2               2.8                4.8               1.8   
146                6.3               2.5                5.0               1.9   
88                 5.6               3.0                4.1               1.3   

     target  
104       2  
126       2  
146       2  
88        1  
['setosa' 'versicolor' 'virginica']
Train size: 70% 
Test size: 30%
Prediction class=[0]


In [70]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("C:\\Users\\kgnan\\OneDrive\\Desktop\\ANN\\pandas\\iris_dataset.csv")
# Prepare data for building the model
X = df.iloc[:,0:4]
print(X.columns)

y = df.iloc[:,4:5]
print(y.head())

# Instantiate scaler and fit on features
scaler = StandardScaler()
scaler.fit(X)

# Transform features
X_scaled = scaler.transform(X.values)





# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,train_size=.7,random_state=25)


print(f"Train size: {round(len(X_train) / len(X) * 100)}% \nTest size: {round(len(X_test) / len(X) * 100)}%")

# Instantiate the model
cls = KNeighborsClassifier()

# Train/Fit the model 
cls.fit(X_train, y_train)

# Make prediction using the model
X_pred = [10.1, 8.2, 5.5, 2.5]
y_pred = cls.predict([X_pred])

print(f"Prediction class={y_pred}")

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')
       Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa
Train size: 70% 
Test size: 30%
Prediction class=['Iris-virginica']


<ipython-input-70-920557b33e5f>:35: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  cls.fit(X_train, y_train)


In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore
df=pd.read_csv("C:\\Users\\kgnan\\OneDrive\\Desktop\\ANN\\pandas\\iris_dataset.csv")
# Prepare data for building the model
X = df.iloc[:,0:4]
print(X.columns)

y = df.iloc[:,4:5]
print(y.head())



X_scaled=X.apply(zscore)
print(X_scaled)


# Split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,train_size=.7,random_state=25)


print(f"Train size: {round(len(X_train) / len(X) * 100)}% \nTest size: {round(len(X_test) / len(X) * 100)}%")

# Instantiate the model
cls = KNeighborsClassifier()

# Train/Fit the model 
cls.fit(X_train, y_train)

# Make prediction using the model
X_pred = [3.1, 8.2, 5.5, 2.5]
y_pred = cls.predict([X_pred])

print(f"Prediction class={y_pred}")

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')
       Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.900681      1.032057      -1.341272     -1.312977
1        -1.143017     -0.124958      -1.341272     -1.312977
2        -1.385353      0.337848      -1.398138     -1.312977
3        -1.506521      0.106445      -1.284407     -1.312977
4        -1.021849      1.263460      -1.341272     -1.312977
..             ...           ...            ...           ...
145       1.038005     -0.124958       0.819624      1.447956
146       0.553333     -1.281972       0.705893      0.922064
147       0.795669     -0.124958       0.819624      1.053537
148       0.432165      0.800654       0.933356      1.447956
149       0.068662     -0.124958       0.762759      0.790591

[150 rows x 4 columns]
Train size: 70% 
Test size: 30%


<ipython-input-1-de70127563b2>:30: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  cls.fit(X_train, y_train)


ValueError: query data dimension must match training data dimension