In [ ]:
# vector opertions: 
# addition, subtraction, dot product, various norms.

In [1]:
# calculate the dot product of two vectors.
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
print(np.dot(vector_a, vector_b))

32

In [2]:
import numpy as np
 
arr1 = np.array([3, 2, 1])
arr2 = np.array([1, 2, 3])
   
s = np.add(arr1, arr2)
t=np.subtract(arr1,arr2)
print(s)  
print(t)

[4 4 4]
[ 2  0 -2]


In [2]:
#cross product of two vectors:output is vector
import numpy as np
 
arr1 = np.array([3, 2, 1])
arr2 = np.array([1, 2, 3])
   
arr1_cross_arr2 = np.cross(arr1, arr2)
print(arr1_cross_arr2)

[ 4 -8  4]


In [4]:
#norms:l2 norm or euclidean norm
import numpy as np
v=np.array([-5, 3, 2])
value=np.linalg.norm(v,np.inf)
print(value)

5.0


In [4]:
a = np.array([2, 5])

v = np.array([8, -6])

# magnitude of "v" vector
magnitude_of_v = np.sqrt(sum(v**2))
print(magnitude_of_v)

proj_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2)*v 

print('Projection of a vector on v vector = ', proj_of_a_on_v)

10.0
Projection of a vector on v vector =  [-1.12  0.84]


In [13]:
a = np.array([2, 5])

v = np.array([8, -6])

# magnitude of "v" vector
#magnitude_of_v = np.sqrt(sum(v**2))
magnitude_of_v=np.linalg.norm(v)
print(magnitude_of_v)

proj_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2)*v 

print('Projection of a vector on v vector = ', proj_of_a_on_v)

10.0
Projection of a vector on v vector =  [-1.12  0.84]


In [9]:
#norms:l1 norm
import numpy as np
v=np.array([-5, 3, 2])
value=np.linalg.norm(v,ord=1)
print(value)


10.0


In [12]:
#norms:l1 norm
import numpy as np
v=np.array([-5, 3, 2])
value=np.linalg.norm(v,np.inf)
print(value)

5.0
