TensorFlow is an open-source machine learning library developed by Google. TensorFlow is used to build and train deep learning models
TensorFlow is basically a software library for numerical computation using data flow graphs where:

nodes in the graph represent mathematical operations.
edges in the graph represent the multidimensional data arrays (called tensors) communicated between them.

**(Please note that tensor is the central unit of data in TensorFlow).**


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


Let’s first create a scalar using tf.constant. We use tf.constant to create a new constant value.

In [1]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

NameError: name 'tf' is not defined

Now let’s create a vector and print its dimensions. You can see that the dimension is 1.

In [ ]:
vector = tf.constant([10,10,20])
print(vector)
print(vector.ndim)

tf.Tensor([10 10 20], shape=(3,), dtype=int32)
1


matrix = tf.constant([
    [10,11],
    [12,13]
])
print(matrix)
print(matrix.ndim)

In [ ]:
matrix = tf.constant([
    [10,11],
    [12,13],
    [5,6]
])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10 11]
 [12 13]
 [ 5  6]], shape=(3, 2), dtype=int32)
2


We have seen that these tensors have a default datatype of int32. What if we want to create a dataset with a custom datatype?

In [ ]:
tensor_1 = tf.constant([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
],dtype='float32')
print(tensor_1)

tf.Tensor(
[[[1. 2. 3.]]

 [[4. 5. 6.]]

 [[7. 8. 9.]]], shape=(3, 1, 3), dtype=float32)


In [ ]:
tensor_1 = tf.constant([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [4,5,6],[5,7,8]
    ],
    [
        [7,8,9],[9,8,0]
    ]
],dtype='float32')
print(tensor_1)

tf.Tensor(
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[4. 5. 6.]
  [5. 7. 8.]]

 [[7. 8. 9.]
  [9. 8. 0.]]], shape=(3, 2, 3), dtype=float32)


Now let’s look at how to create a variable tensor.

In [ ]:
var_tensor = tf.Variable([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])
print(var_tensor)

<tf.Variable 'Variable:0' shape=(3, 1, 3) dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>


In [ ]:
seed = tf.random.Generator.from_seed(42)
normal_tensor = seed.normal(shape=(3,2))
print(normal_tensor)
uniform_tensor = seed.uniform(shape=(3,2))
print(uniform_tensor)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7647915  0.03845465]
 [0.8506975  0.20781887]
 [0.711869   0.8843919 ]], shape=(3, 2), dtype=float32)


We have two tensors created, one with a normal distribution of random numbers and the other with a uniform distribution of random numbers.

Next, we will create a tensor with zeros and ones. In TensorFlow, tensors filled with zeros or ones are often used as a starting point for creating other tensors. They can also be placeholders for inputs in a computational graph.

In [ ]:
zeros = tf.zeros(shape=(3,2))
print(zeros)
ones = tf.ones(shape=(3,2))
print(ones)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Now, let’s look at converting NumPy arrays into tensors.

In [ ]:
import numpy as np
numpy_arr = np.arange(1,25,dtype=np.int32)
print(numpy_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
numpy_tensor = tf.constant(numpy_arr,shape=[2,4,3])
print(numpy_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)


The original NumPy array was 1x12 but our tensor is 2x4x3. This is called re-shaping a tensor which we will often do while training deep neural networks.

Let’s create a 4D tensor with 0 values with the shape 2x3x4x5.

In [ ]:
rank4_tensor = tf.zeros([2,3,4,5])
print(rank4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


We will use tf.size function to get the size. The shape and ndim properties will give us the shape and dimensions of the tensor.

In [ ]:
print("Size",tf.size(rank4_tensor))
print("shape",rank4_tensor.shape)
print("Dimension",rank4_tensor.ndim)