# 1 Checking the TF version and availability of physical devices

#### a Get the version of TensorFlow running on your machine? 

In [ ]:
import tensorflow as tf

print(tf.__version__)


2.12.0


### b. To get the type and number of physical devices available on your machine

In [ ]:
import tensorflow as tf

devices = tf.config.list_physical_devices()


    
print("Number of devices available: ", len(devices))
for device in devices:
    print(device)
    if "GPU" in device.device_type:
        print("GPU is available")
    else:
        print("GPU is not available")


Number of devices available:  1
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
GPU is not available


# 2. Random number generator

### a. What is the need for setting a 'seed' value in any random number generation?
Setting a 'seed' value in any random number generation is important for reproducibility. When we generate random numbers, the values produced are not truly random but are based on some algorithmic calculations. Therefore, if we set the same seed value, we can ensure that the random numbers generated are the same every time we run the code, making the results reproducible. This is particularly useful in scientific research and machine learning, where the ability to reproduce results is crucial.

### b. Create two random number generators using TensorFlow with the same seed of 42, create two random gaussian tensors of shape 2x3, and verify that the both tensors are identical.

In [ ]:
import tensorflow as tf

tf.random.set_seed(42)

# Create two random Gaussian tensors of shape 2x3
tensor1 = tf.random.normal(shape=(2, 3))
tensor2 = tf.random.normal(shape=(2, 3))

# Verify that both tensors are identical
print("Are the two tensors identical? ", tf.reduce_all(tensor1 == tensor2))


tf.Tensor(
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[False False False]
 [False False False]], shape=(2, 3), dtype=bool)
Are the two tensors identical?  tf.Tensor(False, shape=(), dtype=bool)


### c. Create two random number generators using TensorFlow with two different seed values say 42 & 11, create two random gaussian tensors of shape 2x3, and verify that the both tensors are not identical.

In [ ]:
import tensorflow as tf

tf.random.set_seed(42)

# Create first random Gaussian tensor of shape 2x3
tensor1 = tf.random.normal(shape=(2, 3))

tf.random.set_seed(11)

# Create second random Gaussian tensor of shape 2x3
tensor2 = tf.random.normal(shape=(2, 3))

# Verify that both tensors are not identical
print("Are the two tensors identical? ", tf.reduce_all(tensor1 == tensor2))


Are the two tensors identical?  tf.Tensor(False, shape=(), dtype=bool)


# 3. Shuffling of Tensors

### a. Shuffle the given Tensor with and without an operation seed value. Write down your observations.

In [ ]:
#Without seed:

import tensorflow as tf

# Define the input tensor
input_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])

# Shuffle the input tensor without seed
shuffled_tensor = tf.random.shuffle(input_tensor)

# Print the shuffled tensor
print("Shuffled tensor without seed:\n", shuffled_tensor.numpy())


Shuffled tensor without seed:
 [[1 2]
 [7 8]
 [5 6]
 [3 4]]


In [ ]:

#with seed

import tensorflow as tf

# Define the input tensor
input_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])

# Shuffle the input tensor with seed
tf.random.set_seed(42)
shuffled_tensor = tf.random.shuffle(input_tensor)

# Print the shuffled tensor
print("Shuffled tensor with seed:\n", shuffled_tensor.numpy())


Shuffled tensor with seed:
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]


#### Observations:
When shuffling a Tensor without a seed value, the order of elements in the resulting shuffled Tensor will be different each time the operation is executed.
When shuffling a Tensor with a seed value, the order of elements in the resulting shuffled Tensor will be the same every time the operation is executed, as long as the seed value remains the same.
If the same seed value is used for multiple shuffling operations, the order of elements in the shuffled Tensors will be the same.

### b. Show that 'operation seed' in 'tf.random.shuffle' and the 'global seed' in 'tf.random.set_seed' are different? Illustrate that having both gives the tensor in same order every time after shuffling?

In [ ]:
import tensorflow as tf

# Define the input tensor
input_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])

# Shuffle the input tensor with operation seed
tf.random.set_seed(42)
shuffled_tensor_op_seed = tf.random.shuffle(input_tensor, seed=11)

# Shuffle the input tensor with global seed
tf.random.set_seed(42)
shuffled_tensor_global_seed = tf.random.shuffle(input_tensor)
tf.random.set_seed(42)
shuffled_tensor_global_seed2 = tf.random.shuffle(input_tensor)

# Print the shuffled tensors
print("Shuffled tensor with operation seed:\n", shuffled_tensor_op_seed.numpy())
print("Shuffled tensor with global seed:\n", shuffled_tensor_global_seed.numpy())
print("Shuffled tensor with global seed (second execution):\n", shuffled_tensor_global_seed2.numpy())


Shuffled tensor with operation seed:
 [[3 4]
 [1 2]
 [7 8]
 [5 6]]
Shuffled tensor with global seed:
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]
Shuffled tensor with global seed (second execution):
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]


#### Observations:
This code will shuffle the input tensor with both an operation seed and a global seed. We can observe the following:

The shuffled tensor with operation seed is different from the shuffled tensor with global seed.
When we execute the same shuffling operation with the same global seed multiple times, we get the same shuffled tensor every time.
When we execute the same shuffling operation with different global seed values, we get different shuffled tensors.

# 4. Reshaping the tensors

#### a. (i) Construct a vector consisting of first 24 integers using 'numpy'
####     (ii) Convert that ‘numpy’ vector into a Tensor of rank 3.
####     (iii) Write your observations on how the elements of the vector got rearranged in the rank 3 tensor.

In [ ]:
import numpy as np
import tensorflow as tf

# Construct a vector of first 24 integers using NumPy
vector = np.arange(1, 25)

# Convert the NumPy vector to a Tensor of rank 3
tensor_rank3 = tf.reshape(vector, shape=(2, 3, 4))

# Print the reshaped tensor
print("Reshaped Tensor (Rank 3):\n", tensor_rank3.numpy())


Reshaped Tensor (Rank 3):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


###### Observations:

The elements of the vector got rearranged in the rank 3 Tensor in a row-major order, i.e., from left to right, top to bottom, and front to back.
In this specific case, the first 4 integers (1 to 4) became the first row of the first matrix, the next 4 integers (5 to 8) became the second row of the first matrix, and so on.

#### b. (i) Create a tensor of rank 2.
####     (ii) Convert that tensor into another tensor of shape 2x2x1 using 'tf.newaxis'

In [ ]:

import tensorflow as tf

# Create a Tensor of rank 2
tensor_rank2 = tf.constant([[1, 2], [3, 4]])

# Convert the Tensor of rank 2 to another Tensor of shape 2x2x1 using tf.newaxis
tensor_rank3_newaxis = tensor_rank2[:, :, tf.newaxis]

# Print both tensors
print("Tensor (Rank 2):\n", tensor_rank2.numpy())
print("Tensor (Rank 3) with newaxis:\n", tensor_rank3_newaxis.numpy())


Tensor (Rank 2):
 [[1 2]
 [3 4]]
Tensor (Rank 3) with newaxis:
 [[[1]
  [2]]

 [[3]
  [4]]]


#### c. (i) Create a tensor of rank 2.
####     (ii) Convert that tensor into another tensor of shape 2x2x1 using 'tf.expand_dims'

In [ ]:
import tensorflow as tf

# Create a Tensor of rank 2
tensor_rank2 = tf.constant([[1, 2], [3, 4]])

# Convert the Tensor of rank 2 to another Tensor of shape 2x2x1 using tf.expand_dims
tensor_rank3_expand_dims = tf.expand_dims(tensor_rank2, axis=-1)

# Print both tensors
print("Tensor (Rank 2):\n", tensor_rank2.numpy())
print("Tensor (Rank 3) with expand_dims:\n", tensor_rank3_expand_dims.numpy())


Tensor (Rank 2):
 [[1 2]
 [3 4]]
Tensor (Rank 3) with expand_dims:
 [[[1]
  [2]]

 [[3]
  [4]]]


# 5. Linear Regression full experiment

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import mean_squared_error, r2_score

# load the dataset
df = pd.read_csv('/content/drive/MyDrive/Housing_data.csv')

# split the dataset into training and testing sets
X = df.drop('price', axis=1)
y = df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# create the MLP model
model = Sequential()
model.add(Dense(10, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')

# train the MLP model
model.fit(X_train, y_train, epochs=10, batch_size=10)

# make predictions on the testing set
y_pred = model.predict(X_test)

# evaluate the performance of the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print('Mean squared error:', mse)
print('R2 score:', r2)


Epoch 1/10
400/400 [==============================] - 2s 2ms/step - loss: 175442208.0000
Epoch 2/10
400/400 [==============================] - 1s 2ms/step - loss: 100267760.0000
Epoch 3/10
400/400 [==============================] - 1s 2ms/step - loss: 29256264.0000
Epoch 4/10
400/400 [==============================] - 1s 2ms/step - loss: 4048688.2500
Epoch 5/10
400/400 [==============================] - 1s 1ms/step - loss: 1011541.5625
Epoch 6/10
400/400 [==============================] - 1s 1ms/step - loss: 903849.2500
Epoch 7/10
400/400 [==============================] - 1s 1ms/step - loss: 899595.8125
Epoch 8/10
400/400 [==============================] - 1s 1ms/step - loss: 895982.6250
Epoch 9/10
400/400 [==============================] - 1s 1ms/step - loss: 891013.6250
Epoch 10/10
32/32 [==============================] - 0s 1ms/step
Mean squared error: 916920.3181620206
R2 score: 0.1406382908093161


# 6. Regularization full experiment

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# Load the California housing dataset
data = fetch_california_housing()

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Perform Ridge regression
ridge = Ridge(alpha=1.0)
ridge.fit(X_train_scaled, y_train)
ridge_train_predictions = ridge.predict(X_train_scaled)
ridge_test_predictions = ridge.predict(X_test_scaled)
ridge_train_mse = mean_squared_error(y_train, ridge_train_predictions)
ridge_test_mse = mean_squared_error(y_test, ridge_test_predictions)
print("Ridge regression:")
print(f"Train MSE: {ridge_train_mse:.2f}")
print(f"Test MSE: {ridge_test_mse:.2f}")

# Perform Lasso regression
lasso = Lasso(alpha=1.0)
lasso.fit(X_train_scaled, y_train)
lasso_train_predictions = lasso.predict(X_train_scaled)
lasso_test_predictions = lasso.predict(X_test_scaled)
lasso_train_mse = mean_squared_error(y_train, lasso_train_predictions)
lasso_test_mse = mean_squared_error(y_test, lasso_test_predictions)
print("Lasso regression:")
print(f"Train MSE: {lasso_train_mse:.2f}")
print(f"Test MSE: {lasso_test_mse:.2f}")


Ridge regression:
Train MSE: 0.52
Test MSE: 0.56
Lasso regression:
Train MSE: 1.34
Test MSE: 1.31


# 9. Write a Program for text processing to identify the POS tags from the input text?

In [ ]:
import spacy

# Load the language model
nlp = spacy.load('en_core_web_sm')

# Input text
text = "The quick brown fox jumps over the lazy dog."

# Process the text with the language model
doc = nlp(text)

# Print the POS tags for each token
for token in doc:
    print(token.text, token.pos_)


The DET
quick ADJ
brown ADJ
fox NOUN
jumps VERB
over ADP
the DET
lazy ADJ
dog NOUN
. PUNCT


# 10. Write a Program for Text Processing to identify the common tags for the parsing?

In [ ]:
import spacy

# Load the language model
nlp = spacy.load('en_core_web_sm')

# Define input text
text = "The quick brown fox jumps over the lazy dog."

# Process the text with the language model
doc = nlp(text)

# Get the tags for each token
tags = [token.tag_ for token in doc]

# Count the occurrence of each tag
tag_counts = {}
for tag in tags:
    if tag in tag_counts:
        tag_counts[tag] += 1
    else:
        tag_counts[tag] = 1

# Sort the tags by frequency
sorted_tags = sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)

# Print the top 5 most common tags
print("Top 5 most common tags:")
for tag, count in sorted_tags[:5]:
    print(f"{tag}: {count}")


Top 5 most common tags:
JJ: 3
DT: 2
NN: 2
VBZ: 1
IN: 1


# 11. Write a program for Text Processing to identify the Named Entity Recognition from the given Text? 

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Apple is looking at buying U.K. startup for $1 billion"

doc = nlp(text)

for ent in doc.ents:
    print(ent.text, ent.label_)


Apple ORG
U.K. GPE
$1 billion MONEY


# 12. Write the Code for implementing the LSTM model for the sentiment Analysis on IMDB Movie Reviews dataset with Sigmoid Optimizer?

In [ ]:
import numpy as np
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import LSTM, Embedding, Dense
from keras.utils import pad_sequences

# Set the maximum number of words to consider in the dataset
max_features = 5000

# Load the IMDB Movie Reviews dataset
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

# Set the maximum length of a review (in words)
maxlen = 500

# Pad the sequences to have the same length
X_train = pad_sequences(X_train, maxlen=maxlen)
X_test = pad_sequences(X_test, maxlen=maxlen)

# Build the LSTM model
model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

# Compile the model with the sigmoid optimizer
model.compile(loss='binary_crossentropy', metrics=['accuracy'])

# Train the model on the training set
model.fit(X_train, y_train, batch_size=32, epochs=1, validation_data=(X_test, y_test))

# Evaluate the model on the testing set
score, acc = model.evaluate(X_test, y_test, batch_size=32)
print('Test score:', score)
print('Test accuracy:', acc)


782/782 [==============================] - 153s 196ms/step - loss: 0.3309 - accuracy: 0.8636
Test score: 0.3308878540992737
Test accuracy: 0.8636000156402588


# 13. Write the Code for implementing the LSTM model for the sentiment Analysis on IMDB Movie Reviews dataset with Adam Optimizer?

In [ ]:
import numpy as np
from keras.datasets import imdb
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
from keras.optimizers import Adam

# load the IMDB dataset
max_features = 5000
maxlen = 100
batch_size = 64
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)
X_train = pad_sequences(X_train, maxlen=maxlen)
X_test = pad_sequences(X_test, maxlen=maxlen)

# create the LSTM model
model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=1e-4), metrics=['accuracy'])

# train the LSTM model
model.fit(X_train, y_train, batch_size=batch_size, epochs=1, validation_data=(X_test, y_test))

# evaluate the performance of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


391/391 [==============================] - 216s 532ms/step - loss: 0.5765 - accuracy: 0.6919 - val_loss: 0.4363 - val_accuracy: 0.8089
Accuracy: 80.89%


# 14. Write the Code for implementing the LSTM model for the sentiment Analysis on IMDB Movie Reviews dataset with ‘RMSProp’ Optimizer?

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding
from keras.optimizers import RMSprop
from keras.utils import pad_sequences
from keras.datasets import imdb

# Load the dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

# Preprocess the data
max_len = 100
x_train = pad_sequences(x_train, maxlen=max_len)
x_test = pad_sequences(x_test, maxlen=max_len)

# Define the LSTM model
model = Sequential()
model.add(Embedding(10000, 32))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=RMSprop(lr=0.001), loss='binary_crossentropy', metrics=['acc'])

# Train the model
history = model.fit(x_train, y_train, epochs=1, batch_size=128, validation_split=0.2)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/rmsprop.py:143: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


782/782 [==============================] - 10s 13ms/step - loss: 0.3706 - acc: 0.8359
Test accuracy: 0.835919976234436
